server:
    port: ${PORT:8080}
spring:
  application:
      name: events
      date: '@build.date@'
      version: '@build.version@'
  profiles.active: local
logging:
    config: classpath:logback.xml